#注意每个属性：（冒号）后要有一个空格
server:
  port: 9001
#  servlet:
#    context-path: /auth#  servlet:
#    context-path: /auth
  resources:
    static-locations: classpath:/static/, classpath:/templates/
  thymeleaf: